image:
  file: .gitpod.Dockerfile

tasks:
  - init: >
      pyenv global 3.8.8 &&
      pyenv local 3.8.8 &&
      export PIP_USER=false &&
      poetry install
    command: poetry shell

vscode:
  extensions:
    - ms-python.python@2020.10.332292344:5ctthQ25Qni5/aAuOIUTYQ==
