# Check if the code is formatted with black

name: Black check
on: [pull_request]
jobs:
  black-check:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/checkout@v2
      - name: Install Black
        run: pip install black
      - name: Run Black check
        run: black --check src tests
