# Check if the code is pep8 compliant

name: pep8 check
on: [pull_request]
jobs:
  flake8-check:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/checkout@v2
      - name: Install Flake8
        run: pip install flake8
      - name: Run Flake8 check
        run: flake8 src tests
